stages:
  - build
  - deploy

build prod:
  image: node:10.15.0-stretch
  stage: build
  tags:
    - josua
  script:
    - npm install -g @vue/cli@latest
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

deploy prod:
  image: python:latest
  stage: deploy
  environment:
    name: Production
    url: http://vuejs-cicd.s3-website-us-east-1.amazonaws.com/
  tags:
    - josua
  before_script:
    - mkdir ~/.aws
    - echo "$AWS_CREDENTIALS" > ~/.aws/credentials
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://vuejs-cicd --acl public-read

.build stage:
  image: node:10.15.0-stretch
  stage: build
  only:
    - master
  script:
    - npm install -g @vue/cli@latest
    - npm install
    - npm run build-dev
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

.deploy stage:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://YOUR_DEV_BUCKET_NAME --acl public-read
